### ISSUE TITLE
유저의 점수를 저장하고 관리하는 Ranking 시스템

### ISSUE THREAD

**Issue by hyotaime** [binlee0903/se13_team_project#15]
- [x] SQLite를 이용해 `ranking`테이블 생성
- [x] `ranking`테이블에 점수 입력 및 삭제 구현
- [x] 상위 10개의 점수를 가져와 랭킹 데이터 구성
- [x] 랭킹을 보여주는 javaFX Scene 제작

**Comment by hyotaime** [comment]
`ranking`테이블에 사용할 PK인 `id`를 무엇으로 설정해야할까요
**autoincrement**를 사용하려고 하였는데 autoincrement는 수정, 삭제하여도 초기화되지 않기 때문에 잦은 수정 삭제 삽입이 발생하면 int범위를 초과하여 새로운 row를 추가할 수 없게되는 상황이 발생할 우려가 있어 수동적으로 생성해야할 것 같습니다.

아래는 현재 autoincrement를 사용하여 작성한 코드입니다.

```JAVA
package org.se13.sqlite;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RankingRepository {
    // DB connection
    private Connection connect() {
        String url = "jdbc:sqlite:./tetris.db";
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return conn;
    }

    // 초기 테이블 생성
    public void createNewTableRanking() {
        String sql = "CREATE TABLE IF NOT EXISTS ranking ("
                + "	id integer PRIMARY KEY AUTOINCREMENT," // id는 auto increment로 설정해도 괜찮을지?
                + "	name text NOT NULL," // 유저 네임, 게임 종료 후 입력
                + "	points INT NOT NULL" // 점수
                + ");";

        try (Connection conn = this.connect();
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    // 점수 입력
    public void insertRanking(String name, int points) {
        String sql = "INSERT INTO ranking (name, points) VALUES(?,?)";
        try (Connection conn = this.connect();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, name);
            pstmt.setInt(2, points);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public List<Map<String, Object>> getRanking() {
        String sql = "SELECT * FROM ranking ORDER BY points DESC LIMIT 10";
        try (Connection conn = this.connect();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            ResultSet rs = pstmt.executeQuery();

            List<Map<String, Object>> results = new ArrayList<>();
            while (rs.next()) {
                Map<String, Object> result = new HashMap<>();
                result.put("name", rs.getString("name"));
                result.put("points", rs.getInt("points"));
                results.add(result);
            }
            return results;
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }

    public void clearRanking() {
        String sql = "DELETE FROM ranking";
        try (Connection conn = this.connect();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
}
```

**Comment by binlee0903** [comment]
예전 오락실처럼 영어 대문자 3개로 닉네임을 표현하게 하면 좋을 것 같습니다. 이 닉네임은 게임 오버가 되면 사용자로부터 입력을 받은 뒤, 점수와 함께 저장하면 좋을 것 같습니다. 다만 중복된 닉네임을 허용하지 않아야 하기 때문에, 점수 입력 시 이미 존재하는 닉네임인지 확인해야 합니다.

**Comment by hyotaime** [comment]
> 예전 오락실처럼 영어 대문자 3개로 닉네임을 표현하게 하면 좋을 것 같습니다. 이 닉네임은 게임 오버가 되면 사용자로부터 입력을 받은 뒤, 점수와 함께 저장하면 좋을 것 같습니다. 다만 중복된 닉네임을 허용하지 않아야 하기 때문에, 점수 입력 시 이미 존재하는 닉네임인지 확인해야 합니다.

닉네임은 name컬럼으로 구성을 했습니다만 아마 오락실 게임에도 동일한 닉네임을 가진 사람이 여러 점수를 기록해서 저장할 수 있었던 것으로 기억합니다
저도 동일한 닉네임을 가진 사람이 랭킹의 여러 등수를 차지할 수 있도록 구현하고 싶어서요.

**Comment by someh2705** [comment]
Int 값 넘으려면 21억이란 횟수가 어지간해서 넘을 일이 없어서 그 문제에 대해서는 걱정할 필요는 없을 것 같습니다.
그래도 우려되신다면 Long 타입으로 하면 될 것 같아요

**Comment by someh2705** [comment]
그리고 혹시 ConfigRepository를 인터페이스와 구현을 분리해주실 수 있으실까요? (ConfigRepositoryImpl 클래스 추가)
현재 코드상으로는 Repository를 사용하는 곳들이 테스트를 하기 위해선 항상 데이터베이스와 연결이 되어야하므로 테스트하기 어려운 구조가 됩니다.

**Comment by binlee0903** [comment]
그리고 DB 연결은 jdbc를 쌩으로 쓰기 보다는, Hibernate(https://hibernate.org/) 혹은 Mybatis를 사용해서 java POJO로 연결해서 쓰는게 편할거 같은데, 어떻게 생각하시나요? 쿼리 결과를 직접 파싱하는 것보다는 훨씬 편할텐데, 좋다고 생각하시면 제가 구현해 놓겠습니다.

**Comment by hyotaime** [comment]
> 그리고 DB 연결은 jdbc를 쌩으로 쓰기 보다는, Hibernate(https://hibernate.org/) 혹은 Mybatis를 사용해서 java POJO로 연결해서 쓰는게 편할거 같은데, 어떻게 생각하시나요? 쿼리 결과를 직접 파싱하는 것보다는 훨씬 편할텐데, 좋다고 생각하시면 제가 구현해 놓겠습니다.

@binlee0903 
제가 쌩쿼리를 날리는거에 익숙해서 jdbc에 sql문을 그대로 구현했는데 Hibernate를 사용하면 객체로 다룰 수 있어서 더 편리할 것 같습니다.
코멘트를 방금 확인해서 pr을 이미 날렸는데 머지하고 수정하시나요 아니면 닫고 수정 후에 다시 pr날릴까요?

**Comment by binlee0903** [comment]
일단 머지 한 후 제가 수정하겠습니다.

**Comment by STkangyh** [comment]
혹시 랭킹 화면은 어떤 식으로 구현할 예정이신가요? 팝업 광고처럼 띄우실 건지, fxml 파일을 하나 만드실 건지 궁금합니다.

**Comment by hyotaime** [comment]
> 혹시 랭킹 화면은 어떤 식으로 구현할 예정이신가요? 팝업 광고처럼 띄우실 건지, fxml 파일을 하나 만드실 건지 궁금합니다.

새로 게임종료Scene을 생성해서 구현하는 방식으로 생각 중입니다
