### ISSUE TITLE
폴더 구조 개선

### ISSUE THREAD

**Issue by someh2705** [binlee0903/se13_team_project#2]
build.gradle.kts에 정의된 group과 실제 패키지가 다른 문제가 있습니다.
(group은 org.se13이지만 패키지는 se13을 사용중)

그리고 gradle은 멀티모듈을 지원하는 빌드 도구라 실제 애플리케이션인 app 폴더를 따로 두는 것이 좋다고 생각합니다.

**Comment by binlee0903** [comment]
감사합니다.
