### ISSUE TITLE
Setting 값에 필요한 것들

### ISSUE THREAD

**Issue by STkangyh** [binlee0903/se13_team_project#30]
- [x] 해상도 변경 및 해상도가 변경되면서 함께 버튼이나 텍스트의 크기도 함께 커져야함.
- [x] 색맹 모드(적록색맹, 황청색맹)
- [x] 키 세팅 저장
- [x] 저장해서 DB로 보내는 기능
- [x] 초기화해서 default 값을 적용하는 기능

**Comment by someh2705** [comment]
스크롤 뷰로 단락을 나눠서 설정하면 되지 않나요?

**Comment by STkangyh** [comment]
> 스크롤 뷰로 단락을 나눠서 설정하면 되지 않나요?

한 번 적용시켜 보겠습니다.
