### ISSUE TITLE
메뉴에서 키보드로 선택한 버튼의 하이라이트가 잘 안보이는 문제

### ISSUE THREAD

**Issue by binlee0903** [binlee0903/se13_team_project#41]
![image](https://github.com/binlee0903/se13_team_project/assets/44839537/64a642d7-039b-4e58-82fa-e4638a826518)
키보드로 포커싱된 버튼이 잘 안보이는 문제가 있는데, 테두리 border가 바뀌는 것보단, 버튼의 색깔을 주황색으로 바꾸는게 좋지 않을까요?

**Comment by STkangyh** [comment]
확인해보고 알맞은 색깔로 바꿔보겠습니다.

**Comment by STkangyh** [comment]
버튼의 색깔이 문제가 아닌 것 같습니다. 다른 색깔로 진행해봤는데 비슷한 현상이 발생합니다. 테두리 border를 늘리거나 border의 색깔만 바꿀 수 있으면 그렇게 하는 게 좋을 것 같습니다.
