### ISSUE TITLE
Setting 해상도 값 적용을 위해 시작 시 DB update

### ISSUE THREAD

**Issue by STkangyh** [binlee0903/se13_team_project#43]
오늘 회의에서 제가 가볍게 언급했던 내용이었는데, 아무래도 초기값을 어딘가에서 만들어 놓고, 그걸 SettingScreenController나 StackNavGraph에서는 get으로 끌어와서 사용하는 것이 좋을 것 같습니다. 현재 SettingScreenController에서는 initialize 할 때마다 text로 코드 상에서만 설정되어 있는 키로 사용하고 있는데, get으로 끌어오면 코드 재사용적인 측면에서 더 좋을 듯 합니다.

초기값을 어디에 설정해놓으면 좋을까요?

**Comment by binlee0903** [comment]
현재 저희 fxml 파일들은 전부 고정된 값들을 사용하고 있는데, db에서 가져온 다음, 각 Controller에서 Scene의 크기를 바꿔주는 식으로 처리해야 할 것 같습니다. 제가 저번 주에 말씀 드렸던 것처럼 ConfigRepositoryImpl 클래스를 싱글톤으로 바꾼 뒤,
필요한 클래스에서 똑같은 개체를 얻을 수 있으므로, 여기서 화면크기값을 끌어오면 될 것 같습니다.

**Comment by binlee0903** [comment]
일단 StackNavGraph 생성자가 호출될 때, 화면 가로,세로 크기를 초기화 하는 부분을 추가했습니다.
프로그램이 실행되고, 가장 먼저 실행되는 코드이므로 이후 ConfigRepositoryImpl 클래스에서 값을 주고 받으면 될 것 같습니다.

**Comment by STkangyh** [comment]
네 확인했습니다. 그러면 저희 default 설정 id는 0인걸로 확인하고 진행하겠습니다.
