### ISSUE TITLE
대전모드 player 만들기

### ISSUE THREAD

**Issue by STkangyh** [binlee0903/se13_team_project#94]
LevelSelectScreenController 에서 player 객체를 생성하여 대신 들어간다.
Player에는 blockColor mode, key setting, userID 등등 개인마다 적용되어야 할 값들이 들어가야 한다.

- [x] Player에서 사용될 TetrisEventRepository, TetrisActionRepository 필요한 부분 변경
- [x] configRepository에서 id=0,1의 case 생성
- [x] Setting 화면에서 id=0 or 1에 따라서 변경 가능하도록 세팅

**Comment by STkangyh** [comment]
그런데 대전모드에 가면 스코어 보드는 어떻게 업데이트 되어야 하나요?

**Comment by hyotaime** [comment]
대전모드는 스코어보드로 기록을 관리하지 않는다고 합니다

**Comment by binlee0903** [comment]
시간이 남아 제가 대신 구현했습니다.
